-- MySQL Script generated by MySQL Workbench
-- 10/19/17 11:39:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(255) NOT NULL,
  `Title` VARCHAR(255) NULL,
  `Address` VARCHAR(255) NULL,
  `PostalCode` VARCHAR(255) NULL,
  `CountryOrRegion` VARCHAR(255) NULL,
  `StateOrProvince` VARCHAR(255) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InvoiceLineItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InvoiceLineItems` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InvoiceLineItems` (
  `InvoiceID` INT NOT NULL,
  `LineItemID` INT NOT NULL AUTO_INCREMENT,
  `quanity` DECIMAL NOT NULL DEFAULT 1,
  `priceEach` DECIMAL NOT NULL,
  `UOM` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  `lineItem` INT NOT NULL,
  PRIMARY KEY (`LineItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Invoices` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Invoices` (
  `InvoiceID` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(255) NULL,
  `CustomerID` INT NOT NULL,
  `InvoiceDate` DATETIME NOT NULL,
  PRIMARY KEY (`InvoiceID`),
  CONSTRAINT `fk_Invoices_InvoiceLineItems`
    FOREIGN KEY (`InvoiceID`)
    REFERENCES `mydb`.`InvoiceLineItems` (`InvoiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Invoices_Customers1_idx` ON `mydb`.`Invoices` (`CustomerID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`PaymentMethods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PaymentMethods` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PaymentMethods` (
  `PaymentMethodID` INT NOT NULL AUTO_INCREMENT,
  `PaymentMethod` VARCHAR(255) NULL,
  PRIMARY KEY (`PaymentMethodID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchased`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Purchased` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Purchased` (
  `ExpenseID` INT NOT NULL AUTO_INCREMENT,
  `ExpenseTypeID` INT NOT NULL,
  `DatePurchased` DATETIME NOT NULL,
  `DateSubmitted` DATETIME NOT NULL,
  `PaymentMethodID` INT NOT NULL,
  `Amount` FLOAT NOT NULL,
  `PurposeID` INT NULL,
  PRIMARY KEY (`ExpenseID`),
  CONSTRAINT `fk_Purchased_PaymentMethods1`
    FOREIGN KEY (`PaymentMethodID`)
    REFERENCES `mydb`.`PaymentMethods` (`PaymentMethodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Purchased_PaymentMethods1_idx` ON `mydb`.`Purchased` (`PaymentMethodID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`GeneralLedger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GeneralLedger` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GeneralLedger` (
  `EntryID` INT GENERATED ALWAYS AS () VIRTUAL,
  `entryType` VARCHAR(255) NULL,
  `amount` FLOAT NOT NULL,
  `ExpenseID` INT NULL,
  `InvoiceID` INT NULL,
  `entryDate` DATETIME NOT NULL,
  PRIMARY KEY (`EntryID`),
  CONSTRAINT `fk_GeneralLedger_Invoices1`
    FOREIGN KEY (`InvoiceID`)
    REFERENCES `mydb`.`Invoices` (`InvoiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GeneralLedger_Purchased1`
    FOREIGN KEY (`ExpenseID`)
    REFERENCES `mydb`.`Purchased` (`ExpenseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GeneralLedger_Invoices1_idx` ON `mydb`.`GeneralLedger` (`InvoiceID` ASC);

CREATE INDEX `fk_GeneralLedger_Purchased1_idx` ON `mydb`.`GeneralLedger` (`ExpenseID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ExpenseTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ExpenseTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ExpenseTypes` (
  `ExpenseTypeID` INT NOT NULL AUTO_INCREMENT,
  `ExpenseTypes` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ExpenseTypeID`),
  CONSTRAINT `fk_ExpenseTypes_Purchased1`
    FOREIGN KEY (`ExpenseTypeID`)
    REFERENCES `mydb`.`Purchased` (`ExpenseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purposes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Purposes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Purposes` (
  `PurposeID` INT NOT NULL AUTO_INCREMENT,
  `Purpose` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PurposeID`),
  CONSTRAINT `fk_Purposes_Purchased1`
    FOREIGN KEY (`PurposeID`)
    REFERENCES `mydb`.`Purchased` (`PurposeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
